### ISSUE TITLE
Titlebar misaligned in the huddle page

### ISSUE THREAD

**Issue by sayamsamal** [GDSC-KIIT/website#11]
![image](https://user-images.githubusercontent.com/82862779/195973826-683597c4-df53-4d53-929a-2330270f6064.png)

The titlebar in the huddle web page at GDSC KIIT website, seems to be misaligned. I want to fix this issue as part of hacktoberfest 2022. Please assign me this issue as well.

**Comment by junaidrahim** [comment]
You can take this up 👍🏻
