### ISSUE TITLE
[ADDITION + CHANGES] - to GDSC-KIIT Website (Contacts Section)

### ISSUE THREAD

**Issue by hxrshilgupta** [GDSC-KIIT/website#2]
1. To add Youtube Redirect URL with Youtube png [https://www.youtube.com/channel/UCpSfT6lOsDG4pKevAzganGw/](url) to `SocialMediaBar.tsx` under `src/common`
2. GitHub Redirect URL to be corrected from [https://github.com/DSC-KIIT](url) to [https://github.com/GDSC-KIIT](url)

**Comment by junaidrahim** [comment]
this is done
